### ISSUE TITLE
Cloud DNS polling on change status? (change is almost like an LRO)

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-dns#10]
_From @jgeewax on February 15, 2017 11:1_

In Cloud DNS, when I create a change on a zone, I get back a Change -- which should have been a long-running operation, but isn't. This means that I can't easily attach a handler to "should the status of this change, run this callback".

Can we treat a dns#Change resource the same way as a long-running operation? And allow hooking up callbacks to those with some polling something?

_Copied from original issue: GoogleCloudPlatform/google-cloud-node#1999_

**Comment by stephenplusplus** [comment]
_From @danoscarmike on February 27, 2017 22:22_

Pending DNS library support

**Comment by stephenplusplus** [comment]
@danoscarmike we do have support for DNS in the library via `@google-cloud/dns`.

**Comment by carnesen** [comment]
@stephenplusplus @jgeewax, I'm having a hard time understanding this issue. "change" is used as both a tech-specific noun "I get back a Change" and a normal verb "should the status of this change, run this callback" . Dunno what "allow hooking up callbacks to those with some polling something" means. Could you please provide some clarification of the requested bug/feature close this issue?

**Comment by JustinBeckwith** [comment]
We haven't had much feedback here from customers, so I think I'm just going to close this one out.
