### ISSUE TITLE
Typescript 3.7: google-cloud/dns/build/src/zone.d.ts:18:18 - error TS2440

### ISSUE THREAD

**Issue by jgehrcke** [googleapis/nodejs-dns#323]
With Typescript 3.7 there are two compile errors:

```
google-cloud/dns/build/src/zone.d.ts:18:18 - error TS2440: Import declaration conflicts with local declaration of 'CreateChangeCallback'

google-cloud/dns/build/src/zone.d.ts:18:40 - error TS2440: Import declaration conflicts with local declaration of 'CreateChangeRequest'
```

**Comment by bcoe** [comment]
@jgehrcke :wave: I just compiled the latest version of `dns` without any TypeScript issues. Perhaps try:

```
rm package-lock.json
rm -rf node_modules
npm i
```

and make sure you're on the latest version of all the dependencies?

**Comment by JustinBeckwith** [comment]
We backed off to an older version of TypeScript.  If you're still having troubles, let us know!

**Comment by BenSjoberg** [comment]
I just ran into this issue on the latest library version.

I'm using TypeScript 3.7.5 and @google-cloud/dns 1.2.8. Tried `rm -rf`ing package-lock.json and node_modules, but no luck.

Let me know if there's any other info I can provide to assist!

**Comment by soakr** [comment]
Same problem here.
It seems there is redundant declaration of ``CreateChangeCallback`` and ``CreateChangeRequest``.

https://github.com/googleapis/nodejs-dns/blob/master/src/zone.ts

The interfaces is imported at the import section.
https://github.com/googleapis/nodejs-dns/blob/2a6dd7447c80f0d242d459b039837127363f23a1/src/zone.ts#L32

But there is same declaration in the file.

here
https://github.com/googleapis/nodejs-dns/blob/2a6dd7447c80f0d242d459b039837127363f23a1/src/zone.ts#L71

and here

https://github.com/googleapis/nodejs-dns/blob/2a6dd7447c80f0d242d459b039837127363f23a1/src/zone.ts#L53

It seems almost same with declarations on ``change.ts`` and never used.

https://github.com/googleapis/nodejs-dns/blob/2a6dd7447c80f0d242d459b039837127363f23a1/src/change.ts#L30
https://github.com/googleapis/nodejs-dns/blob/2a6dd7447c80f0d242d459b039837127363f23a1/src/change.ts#L23

When I remove these declaration on ``zone.ts``, It worked well.
could you check these codes?

**Comment by sofisl** [comment]
Hello! We have recently upgraded this library to TS ^3.8 and Node 10. Please install the latest version on npm (@google-cloud/dns@2.0.0), and let us know if you run into any other issues!
