### ISSUE TITLE
Create Zone example in the documentation seems to be wrong

### ISSUE THREAD

**Issue by rajitha1998** [googleapis/nodejs-dns#407]
Hello, Google Cloud community!  I have noticed this issue in the `@google-cloud/dns` documentation.
1) Is this a client library issue or a product issue?
* client library documentation issue

2) Did someone already solve this?
* No 
3) Do you have a support contract?
* No
#### Environment details
* Not relevant 
#### Description 

  1.  Visit the [`@google-cloud/dns` documentation](https://cloud.google.com/nodejs/docs/reference/dns/0.7.x/Zone#create)
  2.  Navigate to the create zone function 
   
![Dns](https://user-images.githubusercontent.com/36359382/87650215-ec1ee880-c76e-11ea-9097-f2de851f7cca.JPG)

As you can see in the above image a `DNS` object has been created but it hasn't been used anywhere. Then the create function is called through `zone`. But the `zone` is not initialized anywhere. It seems to be something wrong in this example. It would be great to here suggestions regarding this. 

Thank you :)

**Comment by stephenplusplus** [comment]
Thanks for reporting @rajitha1998! I have sent a PR: #409

**Comment by rajitha1998** [comment]
Great 😀 @stephenplusplus

**Comment by Tower450** [comment]
i realised it too, it is not fixed yet.

**Comment by stephenplusplus** [comment]
@Tower450 what problem are you seeing? The resolution for this issue was adding in the initialization of the `zone` variable. I see that in the link you shared.

**Comment by Tower450** [comment]
The dns variable is not used.

**Comment by Tower450** [comment]
you are right it seems fine.

**Comment by stephenplusplus** [comment]
Phew!
