### ISSUE TITLE
How to create a private zone

### ISSUE THREAD

**Issue by kth-tw** [googleapis/nodejs-dns#495]
I want to create a Private DNS zone.
For example, the equivalent REST request is below
```
POST https://dns.googleapis.com/dns/v1beta2/projects/my-project/managedZones
{
  "description": "",
  "dnsName": "myzone.example.com.",
  "name": "example-zone-name",
  "privateVisibilityConfig": {
    "networks": [
      {
        "networkUrl": "https://www.googleapis.com/compute/v1/projects/my-project/global/networks/default"
      }
    ]
  },
  "visibility": "PRIVATE"
}
```
The question is that the the [CreateZoneRequest](https://cloud.google.com/nodejs/docs/reference/dns/latest/dns/createzonerequest) doesn't have properties -- `privateVisibilityConfig` and `visibility`

**Comment by sofisl** [comment]
HI @kth-tw, unfortunately I don't think this library has this capability yet (this library is autogenerated, so it will get any updates automatically). In the meantime, you can make rest calls or use [this library](https://www.npmjs.com/package/@googleapis/dns), which does have this parameter: https://github.com/googleapis/google-api-nodejs-client/blob/df06a5565509f61a88acd676e31c3eac0f3dc1c5/src/apis/dns/v2.ts#L339
